as yet unclassified
initialize00Title

self addSlideWithCenterBox
	add: (self createHeading: 'From Abstracting to Projectional Editors');
	add: (self createSubheading: 'Seminar Programming Experience');
	add: (self createText: 'Tom Beckmann, Carl Gödecken'); 
	add: (self createText: 'Prof. Dr. Robert Hirschfeld, Jens Lincke, Stefan Ramson');
	add: (self createSmallText: '04. July 2018 - Summer term 2018 - Hasso Plattner Institute - Software Architectures Group')