as yet unclassified
initialize00Title

self addSlideWithCenterBox
	add: (PHLabel pageHeader: 'From Abstracting to Projectional Editors');
	add: (PHLabel subHeading: 'Seminar Programming Experience');
	add: (PHLabel subcategoryHeader: 'Tom Beckmann, Carl Gödecken');
	add: (PHLabel subcategoryHeader: 'Prof. Dr. Robert Hirschfeld, Jens Lincke, Stefan Ramson');
	add: (PHLabel text: '04. July 2018 - Summer term 2018');
	add: (PHLabel text: 'Hasso Plattner Institute - Software Architectures Group')